apiVersion: v1
kind: ServiceAccount
metadata:
  name: addon-lifecycle-operator
  namespace: addon-lifecycle-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-lifecycle-operator
  namespace: addon-lifecycle-operator
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-lifecycle-operator
  namespace: addon-lifecycle-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: addon-lifecycle-operator
subjects:
- kind: ServiceAccount
  name: addon-lifecycle-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-lifecycle-operator
rules:
- apiGroups:
  - "addons.managed.openshift.io"
  resources:
  - addons
  - addons/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-lifecycle-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addon-lifecycle-operator
subjects:
- kind: ServiceAccount
  name: addon-lifecycle-operator
  namespace: addon-lifecycle-operator
