name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
    - run: make setup-dependencies
    - uses: pre-commit/action@v2.0.0
    - run: make ci-test

  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
    - run: make setup-dependencies
    - run: make e2e-test
