name: e2e-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - run: go get golang.org/x/tools/cmd/goimports
    - uses: actions/setup-python@v2
    - run: pip3 install yq
    - uses: actions/checkout@v2
    - run: make e2e-test
